#!/bin/zsh

if [ $# -lt 1 ]
then
    echo "You need to supply a name argument."
    exit 1
fi

mkdir -p ./src/main/scala
mkdir -p ./src/test/scala

echo 'name := "'$1'"

version := "1.0-SNAPSHOT"

scalaVersion := "2.9.2"

organization := "com.mosesn"

libraryDependencies ++= Seq("org.scalatest" %% "scalatest" % "1.7.1" % "test",
                    "junit" % "junit" % "4.8.1" % "test")

scalacOptions += "-deprecation"

' > build.sbt

sbt 'ensime generate'

sbt eclipse
