#!/bin/zsh

if [ $# -lt 1 ]
then
    echo "You need to supply a name argument."
    exit 1
fi

mkdir -p ./src/main/scala
mkdir -p ./src/test/scala
mkdir ./project

echo 'name := "'$1'"

version := "1.0-SNAPSHOT"

scalaVersion := "2.9.1"

libraryDependencies ++= Seq("org.scalatest" %% "scalatest" % "1.7.1" % "test",
                    "junit" % "junit" % "4.8.1" % "test")
' > build.sbt

echo 'addSbtPlugin("org.ensime" % "ensime-sbt-cmd" % "0.0.7")

addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.0.0")' > ./project/plugins.sbt

sbt 'ensime generate'

sbt eclipse